// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AccountMenu: typeof import('./../src/modules/widgets/AccountMenu.vue')['default']
    CryptoDashboardDrawer: typeof import('./../src/layouts/Dashboard/widgets/CryptoDashboardDrawer.vue')['default']
    CryptoDashboardHeader: typeof import('./../src/layouts/Dashboard/widgets/CryptoDashboardHeader.vue')['default']
    GoPathBtn: typeof import('./../src/modules/widgets/GoPathBtn.vue')['default']
    LocaleSwitcher: typeof import('./../src/modules/widgets/LocaleSwitcher.vue')['default']
    NotificationsMenu: typeof import('./../src/modules/widgets/NotificationsMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Starport: typeof import('vue-starport')['Starport']
    StarportCarrier: typeof import('vue-starport')['StarportCarrier']
  }
}
